name: nigerian_widows
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.2
  shared_preferences: ^2.1.1
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/splash/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Black.ttf
        - asset: fonts/Rubik-BlackItalic.ttf
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-BoldItalic.ttf
        - asset: fonts/Rubik-ExtraBold.ttf
        - asset: fonts/Rubik-ExtraBoldItalic.ttf
        - asset: fonts/Rubik-Italic.ttf
        - asset: fonts/Rubik-Light.ttf
        - asset: fonts/Rubik-LightItalic.ttf
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-MediumItalic.ttf
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-SemiBold.ttf
        - asset: fonts/Rubik-SemiBoldItalic.ttf
